name: "🐛 Bug report"
description: Unexpected error/bug/crash while using this script
labels: 
  - "bug"
body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: "A clear and concise description of what the bug is."
    validations:
      required: true

  - type: textarea
    attributes:
      label: To Reproduce
      description: "Describe how the bug was reproduced."
      value: |
        1.
        2.
        3.
        ...
      render: bash
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: "A clear and concise description of what you expected to happen."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Screenshots
      description: "If applicable, add screenshots to help explain your problem."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Happened in what game?
      description: "Include an accessible way so i can reproduce this bug"
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Other game interpreter if used
      description: "Fill out all the boxes that match."
      options:
        - Used Joiplay
        - Used Wine
        - Used MKXP
        - None (default Game.exe started with Windows)

  - type: textarea
    attributes:
      label: Additional context
      description: "Please include helpful information if possible."
    validations:
      required: true
